# Generated by Django 5.0.2 on 2024-03-03 01:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='AtomState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetition_number', models.FloatField()),
                ('ease_factor', models.FloatField()),
                ('inter_repetition_interval', models.FloatField()),
                ('atom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaced_app.atom')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('atom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaced_app.atom')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ease', models.IntegerField()),
                ('atom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaced_app.atom')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaced_app.card')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
