# Generated by Django 5.0.2 on 2024-03-02 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetition_number', models.FloatField()),
                ('ease_factor', models.FloatField()),
                ('inter_repetition_interval', models.FloatField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaced_app.card')),
            ],
        ),
    ]
